import type { Locale } from './i18n';

export interface ManagementPanelView {
  id: string;
  level: 'gestion' | 'avanzado';
  name: string;
  eyebrow: string;
  description: string;
  story: string;
  href: string;
  points: string[];
  tags: string[];
}

const es: ManagementPanelView[] = [
  { id:'planning', level:'gestion', name:'Planning semanal', eyebrow:'Recepción · Gestión', description:'Reservas, huecos, cambios y bloqueos ordenados por unidad y fecha.', story:'El planning convierte la ocupación en una herramienta de trabajo diaria. Recepción puede localizar una estancia, moverla, abrir su ficha o detectar un hueco sin saltar entre hojas y sistemas.', href:'/demos/pinadamar/gestion/#/planning', points:['Ocupación de un vistazo','Cambios sobre el calendario','Detalle de cada reserva'], tags:['Reservas','Disponibilidad','Recepción'] },
  { id:'plano', level:'gestion', name:'Plano de ocupación', eyebrow:'Operaciones · Gestión', description:'El estado real de cada parcela y alojamiento llevado al espacio físico.', story:'El plano traduce el inventario al terreno real del camping. Cada unidad muestra su estado y conecta con el planning para que el equipo entienda qué ocurre y dónde ocurre.', href:'/demos/pinadamar/gestion/#/plano', points:['Estado por unidad','Entradas y salidas','Salto directo al planning'], tags:['Inventario','Mapa','Operaciones'] },
  { id:'solicitudes', level:'gestion', name:'Solicitudes', eyebrow:'Comercial · Gestión', description:'Consultas de la web y seguimiento comercial reunidos en una cola accionable.', story:'Cada consulta llega con su contexto, idioma y estado. El equipo puede priorizar, asignar y responder manteniendo la conversación unida a la futura reserva.', href:'/demos/pinadamar/gestion/#/solicitudes', points:['Contexto de cada consulta','Estado y responsable','Respuesta sin perder el hilo'], tags:['Consultas','Conversión','Seguimiento'] },
  { id:'informes', level:'gestion', name:'Informes operativos', eyebrow:'Gerencia · Gestión', description:'Ocupación, producción y cobros para seguir la marcha del camping.', story:'Los datos esenciales se presentan con periodos comparables y una jerarquía clara. Gerencia puede revisar el negocio sin construir informes paralelos cada semana.', href:'/demos/pinadamar/gestion/#/informes', points:['Indicadores esenciales','Periodos comparables','Datos listos para revisar'], tags:['Ocupación','Ingresos','Gerencia'] },
  { id:'control-total', level:'avanzado', name:'Centro de control', eyebrow:'Dirección · Avanzado', description:'Una visión transversal del pulso operativo y los puntos que requieren atención.', story:'El centro de control conecta señales de recepción, limpieza, mantenimiento y dirección. Destaca prioridades sin sustituir el criterio del equipo ni ejecutar cambios por su cuenta.', href:'/demos/mardefondo/gestion/#/control-total/centro', points:['Pulso operativo','Módulos conectados','Prioridades visibles'], tags:['Dirección','Equipos','Prioridades'] },
  { id:'inteligente', level:'avanzado', name:'Vista inteligente', eyebrow:'Decisión · Avanzado', description:'Recomendaciones explicadas con señales, límites y revisión humana.', story:'La capa inteligente propone y explica. Cada recomendación muestra las señales utilizadas, sus limitaciones y el alcance permitido antes de que una persona decida actuar.', href:'/demos/mardefondo/gestion/#/inteligente', points:['Evidencia trazable','Límites visibles','Control humano siempre'], tags:['IA supervisada','Evidencia','Decisión'] },
];

const en: ManagementPanelView[] = [
  { id:'planning', level:'gestion', name:'Weekly planner', eyebrow:'Reception · Management', description:'Bookings, gaps, changes and blocks organised by unit and date.', story:'The planner turns occupancy into a daily working tool. Reception can find a stay, move it, open its record or spot a gap without switching between spreadsheets and systems.', href:'/demos/pinadamar/gestion/#/planning', points:['Occupancy at a glance','Changes on the calendar','Every booking in detail'], tags:['Bookings','Availability','Reception'] },
  { id:'plano', level:'gestion', name:'Occupancy map', eyebrow:'Operations · Management', description:'The live status of every pitch and accommodation mapped to the physical site.', story:'The map translates inventory into the campsite’s real layout. Every unit shows its status and connects to the planner so the team understands what is happening and where.', href:'/demos/pinadamar/gestion/#/plano', points:['Status by unit','Arrivals and departures','Direct jump to the planner'], tags:['Inventory','Map','Operations'] },
  { id:'solicitudes', level:'gestion', name:'Enquiries', eyebrow:'Sales · Management', description:'Website enquiries and sales follow-up brought together in one actionable queue.', story:'Every enquiry arrives with its context, language and status. The team can prioritise, assign and reply while keeping the conversation connected to the future booking.', href:'/demos/pinadamar/gestion/#/solicitudes', points:['Context for every enquiry','Status and owner','Reply without losing context'], tags:['Enquiries','Conversion','Follow-up'] },
  { id:'informes', level:'gestion', name:'Operational reports', eyebrow:'Leadership · Management', description:'Occupancy, production and payments to track campsite performance.', story:'Essential data is presented through comparable periods and a clear hierarchy. Leadership can review performance without rebuilding parallel reports every week.', href:'/demos/pinadamar/gestion/#/informes', points:['Essential indicators','Comparable periods','Review-ready data'], tags:['Occupancy','Revenue','Leadership'] },
  { id:'control-total', level:'avanzado', name:'Control centre', eyebrow:'Leadership · Advanced', description:'A cross-functional view of operational health and the areas that need attention.', story:'The control centre connects signals from reception, housekeeping, maintenance and leadership. It highlights priorities without replacing the team’s judgement or making changes on its own.', href:'/demos/mardefondo/gestion/#/control-total/centro', points:['Operational pulse','Connected modules','Visible priorities'], tags:['Leadership','Teams','Priorities'] },
  { id:'inteligente', level:'avanzado', name:'Intelligent view', eyebrow:'Decision · Advanced', description:'Recommendations explained with signals, limits and human review.', story:'The intelligent layer proposes and explains. Every recommendation shows the signals used, its limitations and its permitted scope before a person decides to act.', href:'/demos/mardefondo/gestion/#/inteligente', points:['Traceable evidence','Visible limits','Human control throughout'], tags:['Supervised AI','Evidence','Decision'] },
];

export const getManagementPanelViews = (locale: Locale) => locale === 'es' ? es : en;

export const getManagementPanelUi = (locale: Locale) => locale === 'es' ? {
  previous:'Ver los paneles anteriores', next:'Ver los paneles siguientes', region:'Vistas de los paneles de gestión', count:'vistas navegables', open:'Visualizar panel', close:'Cerrar visor', live:'Panel de gestión navegable', browser:'Vista completa y funcional del panel', full:'Abrir panel completo', request:'Quiero este panel', more:'Ver ficha completa', note:'Demostración ficticia: navega y prueba sus vistas sin enviar ni guardar datos reales.',
  catalogKicker:'Paneles de gestión', catalogTitle:'Seis vistas. Una operativa conectada.', catalogText:'Explora cada módulo, descubre qué resuelve y entra en una demostración completa antes de decidir.', backHome:'Volver al home', search:'Buscar panel', searchPlaceholder:'Buscar por nombre o función', filter:'Filtrar paneles por nivel', all:'Todos', management:'Gestión', advanced:'Avanzado', empty:'No hay paneles que coincidan con esta búsqueda.', cardCta:'Ver ficha del panel', noteTitle:'Cada vista se configura alrededor de tu inventario, tus roles y tu manera real de trabajar.',
  back:'Volver a todos los paneles', detailKicker:'Panel de gestión para campings', expand:'Ampliar el panel navegable', solves:'Qué resuelve', howTitle:'La información correcta, en el momento de actuar.', details:'Detalles del panel', level:'Nivel', status:'Estado', statusValue:'Demo navegable', delivery:'Configuración', deliveryValue:'Adaptada a tu camping', includes:'Incluye', related:'Otros paneles', allRelated:'Ver todos los paneles', seoSuffix:'Paneles de gestión para campings — Logic2B Campings',
} : {
  previous:'View previous dashboards', next:'View next dashboards', region:'Management dashboard views', count:'navigable views', open:'Preview dashboard', close:'Close viewer', live:'Navigable management dashboard', browser:'Complete functional dashboard view', full:'Open full dashboard', request:'I want this dashboard', more:'View full dashboard page', note:'Fictional demonstration: browse and try its views without sending or storing real data.',
  catalogKicker:'Management dashboards', catalogTitle:'Six views. One connected operation.', catalogText:'Explore every module, see what it solves and enter a complete demonstration before deciding.', backHome:'Back to home', search:'Search dashboards', searchPlaceholder:'Search by name or function', filter:'Filter dashboards by level', all:'All', management:'Management', advanced:'Advanced', empty:'No dashboards match this search.', cardCta:'View dashboard page', noteTitle:'Every view is configured around your inventory, roles and real way of working.',
  back:'Back to all dashboards', detailKicker:'Campsite management dashboard', expand:'Expand navigable dashboard', solves:'What it solves', howTitle:'The right information at the moment of action.', details:'Dashboard details', level:'Level', status:'Status', statusValue:'Navigable demo', delivery:'Configuration', deliveryValue:'Adapted to your campsite', includes:'Includes', related:'Other dashboards', allRelated:'View all dashboards', seoSuffix:'Campsite management dashboards — Logic2B Campings',
};
